apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-wildfly-app
  namespace: wildfly-ex-app
rules:
- apiGroups: [""]
  resources:
  - nodes
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get"]
