apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-wildfly-app
  namespace: wildfly-ex-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-wildfly-app
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring

